fuzz/*: fuzz rats-tls APIs in host mode
inclavare-containers/rats-tls pull request #183
Opened 2023-09-17 04:04 UTC by cheatguy

use libfuzzer to fuzz rats-tls API `rats_tls_init()`, `rats_tls_negotiate()`,`rats_tls_transmit()` and
 `rats_tls_receive()` in host mode

2023-09-18 02:22 UTC, haosanzi commented on fuzz/README.md
> +## build
Please reorganize it according to the following format

# Building

## Build Requirements

Note that `lib-fuzzer` is part of `clang`, lib-fuzzer is xxxxx(please introduce lib-fuzzer simply)

Follow these steps to install clang:

- Debian / Ubuntu:
```sh
apt install -y xxxx
```

- CentOS / Fedora / RHEL:
```
yum install -y xxx
```

## Build and Install

Add some description in here。

```sh
cmake -DRATS_TLS_BUILD_MODE="host" -DBUILD_SAMPLES=on -DBUILD_FUZZ=on -H. -Bbuild
make -C build install
```
# FUZZ

## rats_tls_init API
## rats_tls_negotiate API
## rats_tls_transmit/recv/clean_up APIs

2023-09-18 02:23 UTC, haosanzi commented on fuzz/tls_init/CMakeLists.txt
> +                    ${CMAKE_CURRENT_SOURCE_DIR}/../../src/include/edl
edl is for SGX mode. There is no need to include edl dir in host mode. Please recheck this.

2023-09-18 02:25 UTC, haosanzi commented on fuzz/tls_init/CMakeLists.txt
> +	DESTINATION /usr/share/rats-tls/fuzz)
please use ${RATS_TLS_INSTALL_FUZZ_PATH} instead of /usr/share/rats-tls/fuzz to facilitate subsequent maintenance

2023-09-25 05:48 UTC, haosanzi commented on fuzz/README.md
> +## Build Requirements
Please add an empty line between titles . For example:
```
# Building

## Build Requirements

Note that `LibFuzzer`xxxx
```

2023-09-25 05:49 UTC, haosanzi commented on fuzz/README.md
> +
please remove this empty line

2023-09-25 05:49 UTC, haosanzi commented on fuzz/README.md
> +to fuzz `rats_tls_init()`, we use random input `* data` to fill the `conf`, and set value to part of the `conf` in order to run `rats_tls_init()` more frequently
`to` changes to `To`.

2023-09-25 05:50 UTC, haosanzi commented on fuzz/README.md
> +start the `/usr/share/rats_tls/fuzz/fuzz_server` first, then use `tls_negotiate` to connect to server and fuzz the `rats_tls_negotiate()` API
`start ` changs to `Start`

2023-09-25 05:50 UTC, haosanzi commented on fuzz/README.md
> +we synthesis the 3 sequential API in one program, start the `/usr/share/rats_tls/fuzz/fuzz_server` first, then use `tls_transmit` to connect to server and fuzz the `rats_tls_transmit()` and `rats_tls
`we` changes to `We`

2023-09-26 09:12 UTC, KB5201314 requested changes

2023-09-26 09:12 UTC, KB5201314 commented on fuzz/tls_init/fuzz_init.cc
> +	FuzzedDataProvider fuzzed_data(data + sizeof(conf), size - sizeof(conf));
Why skip `sizeof(conf)` here? This appears to be part of the old code because the skipped bytes are not used later.

2023-09-26 09:12 UTC, KB5201314 commented on fuzz/tls_init/fuzz_init.cc
> +	if (size < sizeof(rats_tls_conf_t) + 10 * sizeof(claim_t) + 50 * 10 + 100) {
You already have a check for `fuzzed_data.remaining_bytes()`, so a check for `size` seems redundant here?

2023-09-27 02:50 UTC, haosanzi commented on fuzz/README.md
> +```
please add the picture about the fuzz process in your readme.

2023-10-23 02:40 UTC, haosanzi commented on fuzz/CMakeLists.txt
> +add_subdirectory(tls_negotiate)
there is no tls_negotiate dir.

2023-10-24 02:23 UTC, haosanzi commented on fuzz/tls_init/CMakeLists.txt
> +if(SGX)
PR is about Host mode，please delete code about SGX mode

2023-10-24 02:24 UTC, haosanzi commented on fuzz/tls_init/fuzz_init.cc
> +					// strcpy(conf.attester_type,"nullattester");
please remove this Comment code

2023-10-24 02:25 UTC, haosanzi commented on fuzz/tls_negotiate/fuzz_negotiate.cc
> +					// strcpy(conf.crypto_type, "nullcrypto");
please remove this comment code

2023-10-24 02:26 UTC, haosanzi commented on fuzz/tls_transmit/fuzz_transmit.cc
> +// #define test
please remove this comment code

2023-10-30 01:59 UTC, merged