[RFC]rats-tls: add tdx event log support
inclavare-containers/rats-tls pull request #66
Opened 2022-03-12 07:57 UTC by YangLiang3

Fixes: #31
Signed-off-by: Liang Yang <liang3.yang@intel.com>

2022-03-12 10:14 UTC, jiazhang0 commented on src/attesters/tdx-ecdsa/collect_evidence.c
> +    int tdel_info_sz = read(fd, tdel_info, TDEL_INFO_SZ);
You forget to close fd.

2022-03-12 10:20 UTC, jiazhang0 requested changes

2022-03-12 10:20 UTC, jiazhang0 commented on src/attesters/tdx-ecdsa/collect_evidence.c
> +    if (tdel_info_sz != TDEL_INFO_SZ) {
How do you know the size of event log is exactly 0x10000 bytes?

2022-03-12 10:20 UTC, jiazhang0 commented on src/attesters/tdx-ecdsa/collect_evidence.c
> +    memcpy(&(evidence->tdx.quote[8192 + TDEL_INFO_SZ]), tdel_data, tdel_data_sz);
8192 should be replaced by TDX_ECDSA_QUOTE_SZ?

2022-03-12 10:20 UTC, jiazhang0 commented on src/attesters/tdx-ecdsa/collect_evidence.c
> +    memcpy(&(evidence->tdx.quote[8192]), tdel_info, TDEL_INFO_SZ);
8192 should be TDX_ECDSA_QUOTE_SZ?

2022-03-12 10:20 UTC, jiazhang0 commented on src/attesters/tdx-ecdsa/collect_evidence.c
> +
fd should be closed.

2022-03-12 10:20 UTC, jiazhang0 commented on src/attesters/tdx-ecdsa/collect_evidence.c
> +    if (tdel_info_sz != TDEL_INFO_SZ) {
So you miss to parse tdel_info which can tell the exact size of event log to read. You can consult Liang Zhou for the details.

2022-03-12 10:20 UTC, jiazhang0 commented on src/attesters/tdx-ecdsa/collect_evidence.c
> +    }
Lots of format issue causes such changes.

2022-03-12 10:20 UTC, jiazhang0 commented on src/include/rats-tls/cert.h
> +#define TDEL_DATA_SZ      65536
I don't think you need to define these macros again.

2022-03-14 03:14 UTC, haosanzi commented on src/include/rats-tls/cert.h
>  	uint32_t quote_len;
Please fix the format issue.

2022-06-18 08:18 UTC, closed without merging